# Generated by Django 4.2.2 on 2023-06-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=24)),
                ('phone', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
