# Generated by Django 4.2.2 on 2023-06-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
