# Generated by Django 4.2.2 on 2023-08-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_agree_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agree',
            field=models.BooleanField(default=None),
        ),
    ]
