# Generated by Django 4.2.2 on 2023-08-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feed',
            new_name='DiaryContent',
        ),
    ]
