# Generated by Django 4.2.2 on 2023-08-23 14:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0004_alter_content_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='partner_nickname',
            field=models.CharField(default='default_nickname', max_length=24),
        ),
        migrations.AddField(
            model_name='content',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='content',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
